// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_InitiateTransfer_FullMethodName          = "/transaction.TransactionService/InitiateTransfer"
	TransactionService_ProcessDeposit_FullMethodName            = "/transaction.TransactionService/ProcessDeposit"
	TransactionService_ProcessWithdrawal_FullMethodName         = "/transaction.TransactionService/ProcessWithdrawal"
	TransactionService_GetTransactionStatus_FullMethodName      = "/transaction.TransactionService/GetTransactionStatus"
	TransactionService_GetTransactionHistory_FullMethodName     = "/transaction.TransactionService/GetTransactionHistory"
	TransactionService_ReverseTransaction_FullMethodName        = "/transaction.TransactionService/ReverseTransaction"
	TransactionService_ListPendingTransactions_FullMethodName   = "/transaction.TransactionService/ListPendingTransactions"
	TransactionService_ApproveTransaction_FullMethodName        = "/transaction.TransactionService/ApproveTransaction"
	TransactionService_RejectTransaction_FullMethodName         = "/transaction.TransactionService/RejectTransaction"
	TransactionService_GenerateStatement_FullMethodName         = "/transaction.TransactionService/GenerateStatement"
	TransactionService_CalculateTransferFee_FullMethodName      = "/transaction.TransactionService/CalculateTransferFee"
	TransactionService_GetDailyTransactionVolume_FullMethodName = "/transaction.TransactionService/GetDailyTransactionVolume"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	InitiateTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	ProcessDeposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	ProcessWithdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	GetTransactionStatus(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetTransactionHistory(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	ReverseTransaction(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	ListPendingTransactions(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	ApproveTransaction(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	RejectTransaction(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GenerateStatement(ctx context.Context, in *StatementRequest, opts ...grpc.CallOption) (*StatementResponse, error)
	CalculateTransferFee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeResponse, error)
	GetDailyTransactionVolume(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*VolumeResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) InitiateTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, TransactionService_InitiateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ProcessDeposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, TransactionService_ProcessDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ProcessWithdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, TransactionService_ProcessWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactionStatus(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetTransactionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactionHistory(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetTransactionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ReverseTransaction(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, TransactionService_ReverseTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListPendingTransactions(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListPendingTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ApproveTransaction(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TransactionService_ApproveTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) RejectTransaction(ctx context.Context, in *TransactionIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TransactionService_RejectTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GenerateStatement(ctx context.Context, in *StatementRequest, opts ...grpc.CallOption) (*StatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatementResponse)
	err := c.cc.Invoke(ctx, TransactionService_GenerateStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CalculateTransferFee(ctx context.Context, in *FeeRequest, opts ...grpc.CallOption) (*FeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeeResponse)
	err := c.cc.Invoke(ctx, TransactionService_CalculateTransferFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetDailyTransactionVolume(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*VolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetDailyTransactionVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	InitiateTransfer(context.Context, *TransferRequest) (*TransactionResponse, error)
	ProcessDeposit(context.Context, *DepositRequest) (*TransactionResponse, error)
	ProcessWithdrawal(context.Context, *WithdrawalRequest) (*TransactionResponse, error)
	GetTransactionStatus(context.Context, *TransactionIdRequest) (*StatusResponse, error)
	GetTransactionHistory(context.Context, *AccountIdRequest) (*HistoryResponse, error)
	ReverseTransaction(context.Context, *TransactionIdRequest) (*TransactionResponse, error)
	ListPendingTransactions(context.Context, *EmptyRequest) (*HistoryResponse, error)
	ApproveTransaction(context.Context, *TransactionIdRequest) (*StatusResponse, error)
	RejectTransaction(context.Context, *TransactionIdRequest) (*StatusResponse, error)
	GenerateStatement(context.Context, *StatementRequest) (*StatementResponse, error)
	CalculateTransferFee(context.Context, *FeeRequest) (*FeeResponse, error)
	GetDailyTransactionVolume(context.Context, *EmptyRequest) (*VolumeResponse, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) InitiateTransfer(context.Context, *TransferRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateTransfer not implemented")
}
func (UnimplementedTransactionServiceServer) ProcessDeposit(context.Context, *DepositRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessDeposit not implemented")
}
func (UnimplementedTransactionServiceServer) ProcessWithdrawal(context.Context, *WithdrawalRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessWithdrawal not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransactionStatus(context.Context, *TransactionIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransactionHistory(context.Context, *AccountIdRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionHistory not implemented")
}
func (UnimplementedTransactionServiceServer) ReverseTransaction(context.Context, *TransactionIdRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) ListPendingTransactions(context.Context, *EmptyRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingTransactions not implemented")
}
func (UnimplementedTransactionServiceServer) ApproveTransaction(context.Context, *TransactionIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) RejectTransaction(context.Context, *TransactionIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) GenerateStatement(context.Context, *StatementRequest) (*StatementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateStatement not implemented")
}
func (UnimplementedTransactionServiceServer) CalculateTransferFee(context.Context, *FeeRequest) (*FeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateTransferFee not implemented")
}
func (UnimplementedTransactionServiceServer) GetDailyTransactionVolume(context.Context, *EmptyRequest) (*VolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyTransactionVolume not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_InitiateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).InitiateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_InitiateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).InitiateTransfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ProcessDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ProcessDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ProcessDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ProcessDeposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ProcessWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ProcessWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ProcessWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ProcessWithdrawal(ctx, req.(*WithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, req.(*TransactionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetTransactionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransactionHistory(ctx, req.(*AccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ReverseTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ReverseTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ReverseTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ReverseTransaction(ctx, req.(*TransactionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListPendingTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListPendingTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListPendingTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListPendingTransactions(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ApproveTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ApproveTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ApproveTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ApproveTransaction(ctx, req.(*TransactionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_RejectTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).RejectTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_RejectTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).RejectTransaction(ctx, req.(*TransactionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GenerateStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GenerateStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GenerateStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GenerateStatement(ctx, req.(*StatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CalculateTransferFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CalculateTransferFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CalculateTransferFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CalculateTransferFee(ctx, req.(*FeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetDailyTransactionVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetDailyTransactionVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetDailyTransactionVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetDailyTransactionVolume(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateTransfer",
			Handler:    _TransactionService_InitiateTransfer_Handler,
		},
		{
			MethodName: "ProcessDeposit",
			Handler:    _TransactionService_ProcessDeposit_Handler,
		},
		{
			MethodName: "ProcessWithdrawal",
			Handler:    _TransactionService_ProcessWithdrawal_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _TransactionService_GetTransactionStatus_Handler,
		},
		{
			MethodName: "GetTransactionHistory",
			Handler:    _TransactionService_GetTransactionHistory_Handler,
		},
		{
			MethodName: "ReverseTransaction",
			Handler:    _TransactionService_ReverseTransaction_Handler,
		},
		{
			MethodName: "ListPendingTransactions",
			Handler:    _TransactionService_ListPendingTransactions_Handler,
		},
		{
			MethodName: "ApproveTransaction",
			Handler:    _TransactionService_ApproveTransaction_Handler,
		},
		{
			MethodName: "RejectTransaction",
			Handler:    _TransactionService_RejectTransaction_Handler,
		},
		{
			MethodName: "GenerateStatement",
			Handler:    _TransactionService_GenerateStatement_Handler,
		},
		{
			MethodName: "CalculateTransferFee",
			Handler:    _TransactionService_CalculateTransferFee_Handler,
		},
		{
			MethodName: "GetDailyTransactionVolume",
			Handler:    _TransactionService_GetDailyTransactionVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction.proto",
}
