ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(200),
    ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(20) DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS is_suspended BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

